<section class="welcome"><div><span class="eyebrow">PROTEÇÃO QUE ACOMPANHA VOCÊ</span><h2>Olá, <?= e(explode(' ',trim($user['nome_completo']))[0]) ?>.</h2><p><?= $admin?'Tudo o que você precisa para cuidar da segurança da sua equipe.':'Seus equipamentos e solicitações, reunidos em um só lugar.' ?></p><a class="button light" href="<?= $admin?'pedidos.php':'solicitar.php' ?>"><?= $admin?'Gerenciar solicitações':'Solicitar um EPI' ?> <span>→</span></a></div><div class="welcome-symbol" aria-hidden="true">✓</div></section>
<div class="stats-grid">
<?php $stats=$admin?['Funcionários cadastrados'=>count($employees),'EPIs em estoque'=>array_sum(array_column($epis,'quantidade_estoque')),'Pedidos pendentes'=>$counts['Pendente']??0,'Processos em andamento'=>($counts['Aprovada']??0)+($counts['Em andamento']??0)]:['Equipamentos recebidos'=>array_sum(array_column($equipment,'quantidade')),'Tipos de EPI'=>count($equipment),'Solicitações pendentes'=>$counts['Pendente']??0,'Solicitações entregues'=>$counts['Entregue']??0]; foreach($stats as $label=>$number): ?>
<article class="stat"><span><?= e($label) ?></span><strong><?= (int)$number ?></strong><small><?= $admin?'Visão atual do sistema':'Somente seus registros' ?></small></article><?php endforeach ?></div>
<div class="two-columns"><section class="card"><div class="section-heading"><h2><?= $admin?'Solicitações por status':'Solicitações recentes' ?></h2><a href="<?= $admin?'andamento.php':'minhassolicitacoes.php' ?>">Ver todas →</a></div>
<?php if($admin): require __DIR__.'/status-chart.php'; else: $recent=array_slice($requests,0,5); if(!$recent): ?><p class="empty">Você ainda não fez solicitações. <a href="solicitar.php">Solicitar meu primeiro EPI</a></p><?php endif; foreach($recent as $r): ?><div class="list-row"><div><strong><?= e($r['nome_epi']) ?></strong><small><?= (int)$r['quantidade'] ?> un. • <?= e(dateBr($r['data_solicitacao'])) ?></small></div><?= badge($r['status_solicitacao']) ?></div><?php endforeach; endif ?></section>
<section class="card"><div class="section-heading"><h2><?= $admin?'Alertas de estoque':'Avisos importantes' ?></h2><span class="section-icon">!</span></div>
<?php if($admin): $alerts=array_filter($epis,fn($epi)=>$epi['quantidade_estoque']<=$epi['estoque_minimo']); if(!$alerts): ?><div class="notice success">Todos os EPIs estão acima do estoque mínimo.</div><?php endif; foreach($alerts as $epi): ?><div class="list-row"><div><strong><?= e($epi['nome_epi']) ?></strong><small><?= (int)$epi['quantidade_estoque'] ?> disponíveis · mínimo <?= (int)$epi['estoque_minimo'] ?></small></div><a href="fazerpedidos.php?id_epi=<?= (int)$epi['id_epi'] ?>">Repor →</a></div><?php endforeach; else: ?><div class="notice info">Verifique as condições do seu EPI antes de cada uso.</div><p>Equipamento danificado, perdido ou inadequado? Envie uma solicitação com a justificativa para avaliação.</p><p>Uma solicitação aprovada será exibida em “Meu EPI” depois da entrega ser registrada.</p><?php endif ?></section></div>
<section class="card"><div class="section-heading"><h2><?= $admin?'Atividades recentes':'Meus equipamentos' ?></h2><a href="<?= $admin?'movimentacoes.php':'meuepi.php' ?>">Ver detalhes →</a></div>
<?php if($admin): $history=array_slice($history,0,5); require __DIR__.'/history-table.php'; else: if(!$equipment): ?><p class="empty">Nenhum equipamento recebido até o momento.</p><?php endif; foreach($equipment as $epi): ?><div class="list-row"><div><strong><?= e($epi['nome_epi']) ?></strong><small><?= e($epi['descricao']) ?></small></div><span class="badge info"><?= (int)$epi['quantidade'] ?> recebidos</span></div><?php endforeach; endif ?></section>
<div class="quick-links"><?php $quick=$admin?['cadastro.php'=>'＋ Cadastrar funcionário','estoque.php'=>'▦ Consultar estoque','fazerpedidos.php'=>'↗ Fazer pedido de compra']:['meuepi.php'=>'✓ Consultar meus EPIs','solicitar.php'=>'＋ Solicitar equipamento','perfil.php'=>'○ Atualizar perfil']; foreach($quick as $url=>$text): ?><a href="<?= e($url) ?>"><?= e($text) ?></a><?php endforeach ?></div>
