<?php $person=$person??[]; $profile=$page==='perfil'; $value=fn($key)=>$_POST[$key]??($key==='nome'?($person['nome_completo']??''):($person[$key]??'')); ?>
<section class="card form-card"><div class="section-heading"><div><h2><?= $profile?'Seus dados':'Dados do funcionário' ?></h2><p><?= $profile?'Seu cadastro é mantido pelo administrador. Você pode alterar a foto e a senha.':'Preencha os dados de acesso e o vínculo com a equipe.' ?></p></div><img class="avatar large" src="<?= e(avatar($person)) ?>" alt="Foto cadastrada"></div><form method="post" class="form-grid"><?= csrf() ?><input type="hidden" name="id_funcionario" value="<?= (int)($person['id_funcionario']??0) ?>">
<?php foreach(['nome'=>'Nome completo','email'=>'E-mail','cpf'=>'CPF','cargo'=>'Cargo','setor'=>'Setor'] as $key=>$label): ?><label><?= e($label) ?><input type="<?= $key==='email'?'email':'text' ?>" name="<?= e($key) ?>" value="<?= e($value($key)) ?>" maxlength="<?= $key==='cpf'?20:100 ?>" <?= $profile?'readonly':'required' ?> <?= $key==='cpf'?'inputmode="numeric"':'' ?>></label><?php endforeach ?>
<fieldset class="full avatar-options"><legend>Foto de perfil</legend><p>Escolha um avatar ou use uma foto sua.</p><?php foreach([''=>'Não informado','img/boy.png'=>'Masculino','img/woman.png'=>'Feminino'] as $url=>$label): ?><label><input type="radio" name="foto_url" value="<?= e($url) ?>" <?= $value('foto_url')===$url?'checked':'' ?>><img src="<?= e($url?:'img/avatar.svg') ?>" alt=""><span><?= e($label) ?></span></label><?php endforeach ?><label><input type="radio" name="foto_url" value="selfie" id="selfie-option" <?= str_starts_with($person['foto_url']??'','uploads/avatars/')?'checked':'' ?>><img id="selfie-preview" src="<?= e(avatar($person)) ?>" alt="Prévia da sua foto"><span>Minha foto</span></label>
<div class="selfie-tools"><button type="button" class="button secondary" id="open-camera">Tirar selfie</button><label class="button secondary photo-file">Escolher foto<input type="file" id="photo-file" accept="image/jpeg,image/png,image/webp" capture="user"></label></div>
<input type="hidden" name="selfie_data" id="selfie-data">
<div id="camera-panel" hidden><video id="camera-video" autoplay playsinline muted></video><div class="selfie-tools"><button type="button" class="button" id="take-photo">Capturar foto</button><button type="button" class="button secondary" id="close-camera">Cancelar</button></div></div><p id="camera-status" role="status"></p>
</fieldset>
<?php if($profile): ?><label>Senha atual<input type="password" name="senha_atual" autocomplete="current-password"><small>Obrigatória para trocar a senha</small></label><?php endif ?><label><?= $page==='cadastro'?'Senha temporária':'Nova senha (opcional)' ?><input type="password" name="senha" minlength="6" maxlength="72" autocomplete="new-password" <?= $page==='cadastro'?'required':'' ?>><small>Mínimo de 6 caracteres.</small></label><div class="form-actions full"><a class="button secondary" href="<?= $profile?($admin?'home.php':'homefunc.php'):'funcionarios.php' ?>">Voltar</a><button class="button">Salvar <?= $profile?'perfil':'funcionário' ?></button></div></form></section>

<script src="js/profile-photo.js?v=<?= filemtime(__DIR__.'/../../js/profile-photo.js') ?>" defer></script>
